INFO 2022-07-02 17:54:54,628 root : **************************************************
INFO 2022-07-02 17:54:54,628 root : The number given by user is  3 and 9
INFO 2022-07-02 17:54:54,628 root : we are into the function
INFO 2022-07-02 17:54:54,628 root : division operation completed, The result of the code is 0.3333333333333333
INFO 2022-07-02 17:54:54,628 root : **************************************************
INFO 2022-07-02 17:54:54,629 root : The number given by user is  3 and 0
INFO 2022-07-02 17:54:54,629 root : we are into the function
ERROR 2022-07-02 17:54:54,629 root : division by zero
Traceback (most recent call last):
  File "C:/Users/use/PycharmProjects/logging/logging with exception1.py", line 10, in divide
    div = a / b
ZeroDivisionError: division by zero
